-- Baseline migration: matches the Hibernate-generated schema for H2.
-- On existing databases, Flyway baselines at V1 (this migration is skipped).
-- On fresh databases, this migration creates all tables from scratch.

CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    user_id VARCHAR(255),
    CONSTRAINT uk_app_user_channel_id UNIQUE (channel_id)
);

CREATE TABLE scoreboard (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    date DATE NOT NULL,
    finished BOOLEAN NOT NULL,

    -- Wordle
    wordle_raw_content VARCHAR(255),
    wordle_discord_author VARCHAR(255),
    wordle_comment VARCHAR(255),
    wordle_puzzle_number INTEGER,
    wordle_attempts INTEGER,
    wordle_completed BOOLEAN,
    wordle_hard_mode BOOLEAN,

    -- Connections
    connections_raw_content VARCHAR(255),
    connections_discord_author VARCHAR(255),
    connections_comment VARCHAR(255),
    connections_puzzle_number INTEGER,
    connections_mistakes INTEGER,
    connections_completed BOOLEAN,
    connections_solve_order VARCHAR(255),

    -- Strands
    strands_raw_content VARCHAR(255),
    strands_discord_author VARCHAR(255),
    strands_comment VARCHAR(255),
    strands_puzzle_number INTEGER,
    strands_hints_used INTEGER,

    -- Crossword Mini
    crossword_mini_raw_content VARCHAR(255),
    crossword_mini_discord_author VARCHAR(255),
    crossword_mini_comment VARCHAR(255),
    crossword_mini_type VARCHAR(255),
    crossword_mini_time_string VARCHAR(255),
    crossword_mini_total_seconds INTEGER,
    crossword_mini_date DATE,

    -- Crossword Midi
    crossword_midi_raw_content VARCHAR(255),
    crossword_midi_discord_author VARCHAR(255),
    crossword_midi_comment VARCHAR(255),
    crossword_midi_type VARCHAR(255),
    crossword_midi_time_string VARCHAR(255),
    crossword_midi_total_seconds INTEGER,
    crossword_midi_date DATE,

    -- Crossword Daily (Main)
    crossword_daily_raw_content VARCHAR(255),
    crossword_daily_discord_author VARCHAR(255),
    crossword_daily_comment VARCHAR(255),
    crossword_daily_type VARCHAR(255),
    crossword_daily_time_string VARCHAR(255),
    crossword_daily_total_seconds INTEGER,
    crossword_daily_date DATE,
    crossword_daily_duo BOOLEAN,
    crossword_daily_lookups INTEGER,
    crossword_daily_check_used BOOLEAN,

    CONSTRAINT uk_scoreboard_user_date UNIQUE (user_id, date),
    CONSTRAINT fk_scoreboard_user FOREIGN KEY (user_id) REFERENCES app_user (id)
);

CREATE TABLE streak (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    game_type VARCHAR(255) NOT NULL,
    current_streak INTEGER NOT NULL,
    last_updated_date DATE NOT NULL,
    CONSTRAINT uk_streak_user_game_type UNIQUE (user_id, game_type),
    CONSTRAINT fk_streak_user FOREIGN KEY (user_id) REFERENCES app_user (id)
);
