CREATE TABLE win_streak (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    game_type VARCHAR(255) NOT NULL,
    current_streak INTEGER NOT NULL,
    base_streak INTEGER NOT NULL,
    base_date DATE NOT NULL,
    computed_date DATE NOT NULL,
    last_updated_date DATE NOT NULL,
    CONSTRAINT uk_win_streak_user_game_type UNIQUE (user_id, game_type),
    CONSTRAINT fk_win_streak_user FOREIGN KEY (user_id) REFERENCES app_user (id)
);
