CREATE TABLE personal_best (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    game_type VARCHAR(255) NOT NULL,
    day_of_week VARCHAR(255) NOT NULL,
    best_seconds INTEGER NOT NULL,
    best_date DATE,
    source VARCHAR(255) NOT NULL,
    CONSTRAINT uk_personal_best_user_game_dow UNIQUE (user_id, game_type, day_of_week),
    CONSTRAINT fk_personal_best_user FOREIGN KEY (user_id) REFERENCES app_user (id)
);
