-- crossword_history_stats: incrementally maintained per-(user, game, weekday) bucket
-- consumed by the daily scoreboard renderer to display the avg/pb rows.
-- For Mini and Midi we use day_of_week = 0 as a sentinel (one row per user/game).
-- For Main we use 1-7 (Java DayOfWeek.getValue(); Monday=1, Sunday=7).

CREATE TABLE crossword_history_stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    game_type VARCHAR(16) NOT NULL,
    day_of_week TINYINT NOT NULL,
    sample_count INTEGER NOT NULL DEFAULT 0,
    sum_seconds BIGINT NOT NULL DEFAULT 0,
    pb_seconds INTEGER NULL,
    CONSTRAINT fk_crossword_history_stats_user FOREIGN KEY (user_id) REFERENCES app_user (id),
    CONSTRAINT ck_crossword_history_stats_game_type CHECK (game_type IN ('MINI', 'MIDI', 'MAIN')),
    CONSTRAINT ck_crossword_history_stats_day_of_week CHECK (day_of_week BETWEEN 0 AND 7)
);

CREATE UNIQUE INDEX ux_crossword_history_stats_bucket
    ON crossword_history_stats (user_id, game_type, day_of_week);
